services:
  db:
    image: cockroachdb/cockroach:latest-v25.4
    container_name: roach
    hostname: roach
    networks:
      - mynet
    ports:
      - 8081:8080
      - 26257:26257
    volumes:
     - roach:/cockroach/cockroach-data
     - ./apps/backend/migrations:/docker-entrypoint-initdb.d/
    command : start-single-node --insecure

  backend:
    depends_on:
      - db 
    build:
      context: ./apps/backend
    container_name: backend
    hostname: backend
    networks:
      - mynet
    ports:
      - 8080:8080
    environment:
      - PGUSER=${PGUSER:-root}
      - PGPASSWORD=
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE:-mydb}
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  roach:

networks:
  mynet:
    driver: bridge
