# syntax=docker/dockerfile:1

FROM golang:1.26.4 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY cmd/server/*.go ./cmd/server/
COPY internal/themes/*.go ./internal/themes/

RUN CGO_ENABLED=0 GOOS=linux go build -o /moodle-shop-image ./cmd/server

FROM  build-stage AS run-test-stage
RUN go test -v ./interal/themes/...

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /moodle-shop-image /moodle-shop-image

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/moodle-shop-image"]